### ISSUE TITLE
Use slog from std lib

### ISSUE THREAD

**Issue by vianamjr** [lil5/tigerbeetle_grpc#1]
We could use the log/slog lib instead of the x/slog.

**Comment by lil5** [comment]
Thanks for having a look and mentioning this!

I'll be updating the dependencies and will fix this too.

**Comment by vianamjr** [comment]
I would help, but I'm the middle of my non laptop on board vacation 😂

**Comment by lil5** [comment]
4a0a6af3135ef7ce352520840ef4d091ca48111a done
